sudo: false
language: cpp

env:
- TARGET_BRANCH=gh-pages
  HUGO_FLAVOUR=hugo_extended
  HUGO_VERSION="0.45.1"
  BASE_URL=https://cdsp-scpo.github.io/site-DIME-SHS/
  MATOMO_SITE_ID=10
- TARGET_BRANCH=prod
  HUGO_FLAVOUR=hugo_extended
  HUGO_VERSION="0.45.1"
  BASE_URL=https://www.sciencespo.fr/dime-shs/
  MATOMO_SITE_ID=-1

install:
- wget -q -O libstdc++6 http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
- sudo dpkg --force-all -i libstdc++6
- wget --no-clobber https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_FLAVOUR}_${HUGO_VERSION}_Linux-64bit.tar.gz
- tar -xzf ${HUGO_FLAVOUR}_${HUGO_VERSION}_Linux-64bit.tar.gz
- rm ${HUGO_FLAVOUR}_${HUGO_VERSION}_Linux-64bit.tar.gz

script: ./hugo -b $BASE_URL

deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  local-dir: public
  target-branch: $TARGET_BRANCH
  on:
    branch: master
