sudo: false
language: cpp

env:
- TARGET_BRANCH=gh-pages
  HUGO_FLAVOUR=hugo
  HUGO_VERSION="0.48"
  BASE_URL=https://dime-shs.sciencespo.fr/
  MATOMO_SITE_ID=10
- TARGET_BRANCH=prod
  HUGO_FLAVOUR=hugo
  HUGO_VERSION="0.48"
  BASE_URL=https://www.sciencespo.fr/dime-shs/
  MATOMO_SITE_ID=-1

install:
- wget --no-clobber https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_FLAVOUR}_${HUGO_VERSION}_Linux-64bit.tar.gz
- tar -xzf ${HUGO_FLAVOUR}_${HUGO_VERSION}_Linux-64bit.tar.gz
- rm ${HUGO_FLAVOUR}_${HUGO_VERSION}_Linux-64bit.tar.gz

script: ./hugo -b $BASE_URL

deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  local-dir: public
  target-branch: $TARGET_BRANCH
  on:
    branch: master
