language: node_js
node_js: '12'

env:
- TARGET_BRANCH="gh-pages"
  BASE_URL=https://dime-shs.sciencespo.fr/
  NODE_DEBUG="import*"

jobs:
  fast_finish: true
  include:
  - script: npm test
  - name: import-data
    if: type = cron OR branch = master
    script:
    - npm run import
    - git status --short
    after_success:
    - git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
    deploy:
      provider: script
      skip-cleanup: true
      script: npm run deploy:ci
      on:
        branch: master
  - stage: build
    script: npm run build -- -b $BASE_URL
    deploy:
    - provider: pages
      skip-cleanup: true
      github-token: "$GH_TOKEN"
      local-dir: public
      target-branch: "$TARGET_BRANCH"
      on:
        branch: master
