language: node_js
node_js: '12'

env:
- TARGET_BRANCH=prod
  BASE_URL=https://dime-shs.sciencespo.fr/
  MATOMO_SITE_ID=10

matrix:
  fast_finish: true

stages:
- test
- import-data
- build

jobs:
  include:
  - name: test
    script: npm test
  - name: import-data
    if: type = cron OR type = pull_request
    script:
    - npm run import
    - git status --short
    after_success:
    - git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
    deploy:
      provider: script
      skip-cleanup: true
      script: git diff --quiet --staged && git add data && git commit -m 'Mise à jour des publications' && git push origin HEAD:master
      on:
        branch: master
  - name: build
    script: npm run build -- -b $BASE_URL
    deploy:
    - provider: pages
      skip-cleanup: true
      github-token: "$GH_TOKEN"
      local-dir: public
      target-branch: "$TARGET_BRANCH"
      on:
        branch: master
