title: DIME-SHS
email: your-email@example.com
description: >-
  Truc qui apparaît dans les meta description
baseurl: "/site-DIME-SHS" # e.g. /blog
url: "" # e.g. http://example.com

permalink: /:year/:title:output_ext

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-feed

publications:
- id: other
  name: Autre
  sort_order: '4'
- id: beQuali
  name: DIME SHS Quali
  sort_order: '3'
  collections:
    zotero: WB7VJJ7Q
    spire:  SCIENCESPO:DIME-SHS-beQuali
- id: elipss
  name: DIME SHS Quanti
  sort_order: '2'
  collections:
    zotero: EKTQQHP7
    spire:  SCIENCESPO:DIME-SHS-Elipss
- id: dime-web
  name: DIME SHS Web
  sort_order: '1'
  collections:
    zotero: 7PZVF5PD
    spire:  SCIENCESPO:DIME-SHS-DIME-Web

defaults:
- scope:
    path: ""
  values:
    layout: "page"
- scope:
    path: ""
    type: "posts"
  values:
    layout: "page"

prose:
  media: img

exclude:
  - Gemfile
  - Gemfile.lock
  - docs
  - node_modules
  - package.json
  - package-lock.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
