title: DIME-SHS
email: your-email@example.com
description: >-
  Truc qui apparaît dans les meta description
baseurl: "/site-DIME-SHS" # e.g. /blog
url: "" # e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-feed

defaults:
- scope:
    path: ""
  values:
    layout: "page"
- scope:
    path: ""
    type: "posts"
  values:
    layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
