[build]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"
  publish = "public"

  [build.environment]
  HUGO_VERSION = "0.45"

  [context.deploy-preview]
  command = "hugo --i18n-warnings --baseURL $DEPLOY_PRIME_URL"

  [context.deploy-preview.environment]
  HUGO_IS_PREVIEW = "1"
