[build]
  command = "npm run build -- --baseURL $DEPLOY_URL"
  publish = "public"

  [context.deploy-preview]
  command = "npm run build -- --i18n-warnings --baseURL $DEPLOY_PRIME_URL"

  [context.deploy-preview.environment]
  HUGO_IS_PREVIEW = "1"
