[build]
  command = "npm run build -- --baseURL $DEPLOY_URL"
  publish = "public"

  [context.deploy-preview]
  command = "npm run build -- --i18n-warnings --baseURL $DEPLOY_PRIME_URL"

  [context.deploy-preview.environment]
  HUGO_IS_PREVIEW = "1"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404
